# Default values for helloapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: am17docker/helloapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: LoadBalancer
  port: 3000
  name: helloapp-service
  targetport: 3000
  
container:
  containerPort: 3000   