replicaCount: 1

image:
  repository: am17docker/greet-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: LoadBalancer
  port: 8080
  name: helloapp-service
  targetport: 8080
  
container:
  containerPort: 8080
  greetingsName: Anurag
  greetingsDateformat: dd/MM/yyyy HH:mm   